--- 
brakeman:
  enabled: true
csslint:
  enabled: true
duplication:
  config:
    languages:
      - ruby
      - javascript
      - coffeescript
  enabled: true
eslint:
  enabled: true
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
  - public/**/*
ratings:
  paths:
    - app/**
    - lib/**
    - "**.rb"
    - "**.go"
rubocop:
  enabled: true
